#----------------------------------
# GitHub Action Part-1 - Basics
#
# Copyleft (c) by Roman 2024.
#----------------------------------

name: My-GitHubActions-Basics

env:
  APPLICATION_NAME    : "MyFirstGHA"
  DEPLOY_PACKAGE_NAME : "first-gha-ver-${{ github.sha }}"

on:
  push:
    branches:
      - main

jobs:                        #перечисление jobs
  my_testing:                #название job
    runs-on: ubuntu-22.04
    steps:
    - name: Print Hello World #название
      run: | #вывод HW через ЛИНУКС КОМАНДЫ
        echo "Hello world"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
      

  my_deploy:                  #название job
    runs-on: ubuntu-22.04
    needs: [my_testing]
    steps:
    - name: Print Hello World 
      run: |
        echo "Hello world" 
        echo "Deploy package name ${{ env.DEPLOY_PACKAGE_NAME }}"

  
