#----------------------------------
# GitHub Action Part-1 - Basics
#
# Copyleft (c) by Roman 2024.
#----------------------------------

name: My-GitHubActions-Basics
on:
  push:
    branches:
      - master
