#----------------------------------
# GitHub Action Part-1 - Basics
#
# Copyleft (c) by Roman 2024.
#----------------------------------

name: My-GitHubActions-Basics
on:
  push:
    branches:
      - main

jobs:                        #перечисление jobs
  my_testing:                #название job
    runs-on: ubuntu-22.04
    steps:
    - name: Print Hello World #название
      run: echo "Hello world" #вывод HW через ЛИНУКС КОМАНДЫ


  my_deploy:                  #название job
    runs-on: ubuntu-22.04
    needs: [my_testing]
    steps:
    - name: Print Hello World 
      run: echo "Hello world"


  
